version: "3.8"

services:
  backend:
    build: ./backend
    container_name: cosa_backend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5000
      - DATABASE_URL=mysql+pymysql://root:makaeenm1@db:3306/cosa
      - HOST_IP=${HOST_IP}  # Lấy từ biến môi trường
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./cosa
    container_name: cosa_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://${HOST_IP}:5000  # API base URL linh hoạt
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: cosa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: makaeenm1
      MYSQL_DATABASE: cosa
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:
